### ISSUE TITLE
can it integrate with kcptun? /滑稽

### ISSUE THREAD

**Issue by skyduy** [ihciah/go-shadowsocks-magic#1]

**Comment by wen-fei** [comment]
sorry, No

**Comment by ihciah** [comment]
Yes, but meaningless.
Kcptun can transfer UDP data in a multi-thread way. But using UDP, you might have to handle UDP Qos problems.
Go-shadowsocks-magic is designed as an simple extended version of the original shadowsocks. There's no need to convert data to UDP if you want to transfer data in parallel.
