### ISSUE TITLE
shadowsocks-magic-win64.exe闪退

### ISSUE THREAD

**Issue by kaitofung** [ihciah/go-shadowsocks-magic#4]
windows客户端应该怎么做？打开shadowsocks-magic-win64.exe出现闪退（go环境已有）

**Comment by ihciah** [comment]
直接启动程序会在错误输出后直接关闭窗口。
请通过命令行启动。
ps：运行编译好的客户端其实不需要go环境

**Comment by ihciah** [comment]
@kaitofung 
本项目已经终止，请移步更稳定通用的 [Rabbit TCP](https://github.com/ihciah/rabbit-tcp)
