### ISSUE TITLE
这个报错是什么原因呢

### ISSUE THREAD

**Issue by PHCSJC** [ihciah/go-shadowsocks-magic#6]
root@aml:~# ./shadowsocks-magic-arm -c 'ss://AEAD_CHACHA20_POLY1305:12345678@107.173.*.*:8488' -verbose -socks :1090
2019/06/11 09:05:54 tcp.go:20: SOCKS proxy :1080 <-> 107.173.*.*:8488
2019/06/11 09:05:54 tcp.go:152: failed to get target address: EOF
2019/06/11 09:05:55 tcp.go:152: failed to get target address: EOF
2019/06/11 09:05:55 tcp.go:152: failed to get target address: EOF
2019/06/11 09:05:55 tcp.go:152: failed to get target address: EOF
2019/06/11 09:05:55 tcp.go:152: failed to get target address: unexpected EOF
2019/06/11 09:05:55 tcp.go:152: failed to get target address: SOCKS error: 8
2019/06/11 09:05:55 tcp.go:152: failed to get target address: SOCKS error: 8
2019/06/11 09:05:55 tcp.go:152: failed to get target address: SOCKS error: 8

另外，服务端没有任何提示，服务器端是x86，客户端是arm64

**Comment by PHCSJC** [comment]
搜了下这个错误好像是go-shadowsocks2的BUG，老哥能看看吗？

**Comment by zhaojh329** [comment]
我也遇到了

**Comment by ihciah** [comment]
@PHCSJC @zhaojh329 
本项目已经终止，请移步更稳定通用的 [Rabbit TCP](https://github.com/ihciah/rabbit-tcp)
